RentX/Controllers/ItemsController.cs
using Microsoft.AspNet.Identity;
using RentX.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace RentX.Controllers
{
    public class ItemsController : Controller
    {
        ApplicationDbContext context;
        public ItemsController()
        {
            context = new ApplicationDbContext();
        }

        // GET: Items
        public ActionResult Index()
        {
            return View(context.Items.ToList());
        }

        // GET: Items/Details/5
        public ActionResult Details(int id)
        {
            Item item = context.Items.Where(i => i.ItemId == id).FirstOrDefault();
            return View(item);
        }

        // GET: Items/Create
        public ActionResult Create()
        {
            Item item = new Item();
            item.Availability = true;
            return View(item);
        }

        // POST: Items/Create
        [HttpPost]
        public ActionResult Create(Item item)
        {
            try
            {
                // TODO: Add insert logic here  
                string id = User.Identity.GetUserId();
                var leaser = context.Leasors.Where(u => u.ApplicationId == id).FirstOrDefault();
                //var renter = context.Renters.Where(r => r.ApplicationId == id).FirstOrDefault();
                item.LeasorId = leaser.LeasorId;
                //item.RenterId = renter.RenterId;
                context.Items.Add(item);                
                context.SaveChanges();
                Queue queue = new Queue();
                queue.ItemId = item.ItemId;
                context.Queues.Add(queue);
                context.SaveChanges();
                return RedirectToAction("Index", "Home");
            }
            catch
            {

                return View();
            }
        }

        // GET: Items/Edit/5
        public ActionResult Edit(int id)
        {
            Item item = context.Items.Where(i => i.ItemId == id).FirstOrDefault();
            return View(item);
        }

        // POST: Items/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, Item item)
        {
            try
            {
                // TODO: Add update logic here
                Item itemToEdit = context.Items.Where(i => i.ItemId == id).FirstOrDefault();
                itemToEdit.Name = item.Name;
                itemToEdit.Price = item.Price;
                itemToEdit.Image = item.Image;
                itemToEdit.RentCounter = item.RentCounter;
                itemToEdit.Availability = item.Availability;
                itemToEdit.NumOfMonthsForRent = item.NumOfMonthsForRent;
                itemToEdit.StartDate = item.StartDate;
                itemToEdit.EndDate = item.EndDate;
                context.SaveChanges();

                return RedirectToAction("Index", "Home");
            }
            catch
            {
                return View();
            }
        }

        // GET: Items/Delete/5
        public ActionResult Delete(int id)
        {
            Item item = context.Items.Where(i => i.ItemId == id).FirstOrDefault();
            return View(item);
        }

        // POST: Items/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, Item item)
        {
            try
            {
                // TODO: Add delete logic here
                Item itemToDelete = context.Items.Where(i => i.ItemId == id).FirstOrDefault();
                context.Items.Remove(itemToDelete);
                context.SaveChanges();
                return RedirectToAction("Index", "Home");
            }
            catch
            {
                return View();
            }
        }
    }
}

RentX/Controllers/LeasorsController.cs
using Microsoft.AspNet.Identity;
using Newtonsoft.Json.Linq;
using RentX.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

using System.Net;

namespace RentX.Controllers
{
    public class LeasorsController : Controller
    {
        ApplicationDbContext context;
        SMSController sendText;
        RatingsController rate;
        public LeasorsController()
        {
            context = new ApplicationDbContext();
            sendText = new SMSController();
            rate = new RatingsController();
        }
        public ActionResult GetRatingQueue()
        {
            string appId = User.Identity.GetUserId();
            Leasor leasor = context.Leasors.Where(r => r.ApplicationId == appId).FirstOrDefault();
            List<RatingQueue> ratingQueues = context.RatingQueues.Where(r => r.LeasorId == leasor.LeasorId).ToList();
            return View(ratingQueues);
        }
        public ActionResult UnRentItem()
        {
            string appId = User.Identity.GetUserId();
            Leasor leasor = context.Leasors.Where(r => r.ApplicationId == appId).FirstOrDefault();
            List<Item> items = context.Items.Where(i => i.LeasorId == leasor.LeasorId).ToList();
            
            foreach (Item item in items)
            {
                if(DateTime.Now >= item.EndDate)
                {
                    Renter renter = context.Renters.Where(r => r.RenterId == item.RenterId).FirstOrDefault();
                    item.Availability = true;
                    item.StartDate = null;
                    item.EndDate = null;
                    item.RenterId = null;
                    RatingQueue ratingQueue = new RatingQueue();
                    ratingQueue .LeasorId = leasor.LeasorId;
                    ratingQueue.RenterId = renter.RenterId;
                    context.RatingQueues.Add(ratingQueue);
                    context.SaveChanges();
                    sendText.SendSMSToRenterForRentPeriodEnding(renter);
                    //RedirectToAction("Create", "Ratings", rating);
                }
            }
            return RedirectToAction("Index", "Home");
        }
        public ActionResult RentOutItem(int id, int ItemId)
        {
            Renter renter = context.Renters.Where(r => r.RenterId == id).FirstOrDefault();
            Item item = context.Items.Where(i => i.ItemId == ItemId).FirstOrDefault();
            item.RentCounter++;
            item.StartDate = DateTime.Now;
            item.EndDate = DateTime.Now.AddMonths(item.NumOfMonthsForRent);
            item.Availability = false;
            item.RenterId = renter.RenterId;
            context.SaveChanges();
            //sendText.SendSMSToRenterForItemNowRented(renter);
            return RedirectToAction("Index", "Home");
        }
        public ActionResult RequestRenterPayment(int id, int ItemId)
        {
            Renter renter = context.Renters.Where(r => r.RenterId == id).FirstOrDefault();
            Item item = context.Items.Where(i => i.ItemId == ItemId).FirstOrDefault();
            PaymentRequest paymentRequest = new PaymentRequest();
            paymentRequest.RenterId = renter.RenterId;
            paymentRequest.ItemId = item.ItemId;
            context.PaymentRequests.Add(paymentRequest);
            context.SaveChanges();
            //sendText.SendSMSToRenterForPaymentRequest(renter);
            return RedirectToAction("Index", "Home");
        }
        public ActionResult GetItemQueue(int id)
        {
            ItemQueueViewModel itemQueueViewModel = new ItemQueueViewModel() { Renters = new List<Renter>(), ItemId = 0};
            Item item = context.Items.Where(i => i.ItemId == id).FirstOrDefault();
            itemQueueViewModel.ItemId = item.ItemId;
            Queue queue = context.Queues.Where(q => q.ItemId == item.ItemId).FirstOrDefault();
            List<QueueRenter> queueRenter = context.QueueRenters.Where(q => q.QueueId == queue.QueueId).ToList();
            List<Renter> renters = new List<Renter>();
            foreach (QueueRenter model in queueRenter)
            {
                var renter = context.Renters.Where(r => r.RenterId == model.RenterId).FirstOrDefault();
                renters.Add(renter);
            }
            
            foreach (Renter model in renters)
            {
                itemQueueViewModel.Renters.Add(model);
                
            }
            return View(itemQueueViewModel);
        }
        public ActionResult GetLeasorItems(int id)
        {
            
            Leasor leasor = context.Leasors.Where(l => l.LeasorId == id).FirstOrDefault();
            List<Item> leasorItems = context.Items.Where(l => l.LeasorId == leasor.LeasorId).ToList();
            return View(leasorItems);
        }
        // GET: Leasors
        public ActionResult Index()
        {
            return View(context.Leasors.ToList());
        }

        // GET: Leasors/Details/5
        public ActionResult Details(int id)
        {
            Leasor leasor = context.Leasors.Where(l => l.LeasorId == id).FirstOrDefault();
            return View(leasor);
        }

        // GET: Leasors/Create
        public ActionResult Create()
        {
            Leasor leasor = new Leasor();
            return View(leasor);
        }

        // POST: Leasors/Create
        [HttpPost]
        public async Task<ActionResult> Create(Leasor leasor)
        {
            try
            {
                // TODO: Add insert logic here                
                context.Leasors.Add(leasor);
                string requesturl = "https://maps.googleapis.com/maps/api/geocode/json?address=";
                string userAddress = System.Web.HttpUtility.UrlEncode(
                    leasor.StreetAddress + " " +
                    leasor.City + " " +
                    leasor.StateCode + " " +
                    leasor.ZipCode);
                string apiKey = APIKeys.GeoCodeApi;
                HttpClient client = new HttpClient();
                var response = await client.GetStringAsync(requesturl + userAddress + apiKey);
                JObject map = JObject.Parse(response);
                leasor.Lat = (float)map["results"][0]["geometry"]["location"]["lat"];
                leasor.Lng = (float)map["results"][0]["geometry"]["location"]["lng"];
                string id = User.Identity.GetUserId();
                leasor.ApplicationId = id;
                context.SaveChanges();

                return RedirectToAction("Index", "Home");
            }
            catch
            {
                return View();
            }
        }

        // GET: Leasors/Edit/5
        public ActionResult Edit(int id)
        {
            Leasor leasor = context.Leasors.Where(l => l.LeasorId == id).FirstOrDefault();
            return View(leasor);
        }

        // POST: Leasors/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, Leasor leasor)
        {
            try
            {
                // TODO: Add update logic here
                Leasor leasorToEdit = context.Leasors.Where(l => l.LeasorId == id).FirstOrDefault();
                leasorToEdit.FirstName = leasor.FirstName;
                leasorToEdit.LasttName = leasor.LasttName;
                leasorToEdit.EmailAddress = leasor.EmailAddress;
                leasorToEdit.StreetAddress = leasor.StreetAddress;
                leasorToEdit.ZipCode = leasor.ZipCode;
                leasorToEdit.StateCode = leasor.StateCode;
                context.SaveChanges();                
                return RedirectToAction("Index", "Home");
            }
            catch
            {
                return View();
            }
        }

        // GET: Leasors/Delete/5
        public ActionResult Delete(int id)
        {
            Leasor leasor = context.Leasors.Where(l => l.LeasorId == id).FirstOrDefault();
            return View(leasor);
        }

        // POST: Leasors/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, Leasor leasor)
        {
            try
            {
                // TODO: Add delete logic here
                Leasor leasorToDelete = context.Leasors.Where(l => l.LeasorId == id).FirstOrDefault();
                context.Leasors.Remove(leasorToDelete);
                context.SaveChanges();
                return RedirectToAction("Index", "Home");
            }
            catch
            {
                return View();
            }
        }
    }
}

RentX/Controllers/RatingsController.cs
using Microsoft.AspNet.Identity;
using RentX.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace RentX.Controllers
{
    public class RatingsController : Controller
    {
        ApplicationDbContext context;
        public RatingsController()
        {
            context = new ApplicationDbContext();
        }

        public ActionResult GetRenterRatings(int id)
        {
            List<Rating> ratings = context.Ratings.Where(r => r.RenterId == id).ToList();
            return View(ratings);
        }
        public ActionResult GetLeasorRatings(int id)
        {
            List<Rating> ratings = context.Ratings.Where(r => r.LeasorId == id).ToList();
            return View(ratings);
        }
        // GET: Ratings
        public ActionResult Index()
        {
            return View(context.Ratings.ToList());
        }

        // GET: Ratings/Details/5
        public ActionResult Details(int id)
        {
            Rating rating = context.Ratings.Where(r => r.RatingId == id).FirstOrDefault();
            return View();
        }

        // GET: Ratings/Create
        public ActionResult Create()
        {
            Rating rating = new Rating();
            return View(rating);
        }

        // POST: Ratings/Create
        [HttpPost]
        public ActionResult Create(Rating rating)
        {
            try
            {
                // TODO: Add insert logic here
                
                
                string id = User.Identity.GetUserId();
                var leaser = context.Leasors.Where(u => u.ApplicationId == id).FirstOrDefault();
                var renter = context.Renters.Where(r => r.ApplicationId == id).FirstOrDefault();
                rating.LeasorId = leaser.LeasorId;
                rating.RenterId = renter.RenterId;
                context.Ratings.Add(rating);
                context.SaveChanges();
                return RedirectToAction("Index", "Home");
            }
            catch
            {
                return View();
            }
        }

        // GET: Ratings/Edit/5
        public ActionResult Edit(int id)
        {
            Rating rating = context.Ratings.Where(r => r.RatingId == id).FirstOrDefault();
            return View(rating);
        }

        // POST: Ratings/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, Rating rating)
        {
            try
            {
                // TODO: Add update logic here
                Rating ratingToEdit = context.Ratings.Where(r => r.RatingId == id).FirstOrDefault();
                ratingToEdit.NumOfStars = rating.NumOfStars;
                ratingToEdit.Review = rating.Review;
                return RedirectToAction("Index", "Home");
            }
            catch
            {
                return View();
            }
        }

        // GET: Ratings/Delete/5
        public ActionResult Delete(int id)
        {
            Rating rating = context.Ratings.Where(r => r.RatingId == id).FirstOrDefault();
            return View(rating);
        }

        // POST: Ratings/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, Rating rating)
        {
            try
            {
                // TODO: Add delete logic here
                Rating ratingToDelete = context.Ratings.Where(r => r.RatingId == id).FirstOrDefault();
                context.Ratings.Remove(ratingToDelete);
                context.SaveChanges();
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
        public ActionResult CreateRatingForLeasor()
        {
            //Renter renter = context.Renters.Where(r => r.RenterId == id).FirstOrDefault();
            Rating rating = new Rating();
            return View(rating);
        }

        // POST: Ratings/Create
        [HttpPost]
        public ActionResult CreateRatingForLeasor(Rating rating, int id)
        {
            try
            {
                // TODO: Add insert logic here                
                Renter renter = context.Renters.Where(r => r.RenterId == id).FirstOrDefault();
                rating.RenterId = renter.RenterId;
                context.Ratings.Add(rating);
                context.SaveChanges();
                return RedirectToAction("Index", "Home");
            }
            catch
            {
                return View();
            }
        }
    }
}

RentX/Views/Leasors/Create.cshtml
@model RentX.Models.Leasor

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Leasor</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LasttName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LasttName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LasttName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EmailAddress, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EmailAddress, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EmailAddress, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StreetAddress, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StreetAddress, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StreetAddress, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.City, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.City, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StateCode, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StateCode, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StateCode, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ZipCode, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ZipCode, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ZipCode, "", new { @class = "text-danger" })
            </div>
        </div>

        

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

RentX/Views/Leasors/Delete.cshtml
@model RentX.Models.Leasor

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Leasor</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LasttName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LasttName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EmailAddress)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EmailAddress)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StreetAddress)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StreetAddress)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.City)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.City)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StateCode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StateCode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ZipCode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ZipCode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Lat)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Lat)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Lng)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Lng)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ApplicationId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ApplicationId)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

RentX/Views/Leasors/Details.cshtml
@model RentX.Models.Leasor

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>
<style>
    /* Always set the map height explicitly to define the size of the div
            * element that contains the map. */
    #map {
        height: 400px;
        width: 400px;
        margin: 20px;
    }
    /* Optional: Makes the sample page fill the window. */
    html, body {
        height: 100%;
        margin: 20px;
        padding: 10px;
    }
</style>
<div id="map"></div>
<script>
      var map;
      function initMap() {
          map = new google.maps.Map(document.getElementById('map'), {
              center: { lat: @Model.Lat , lng: @Model.Lng },
              zoom: 8

          });
      var marker = new google.maps.Marker({
        position: {
            lat: @Model.Lat,
            lng: @Model.Lng
        },
        map: map
    });
        }
</script>
<script src="https://maps.googleapis.com/maps/api/js?@APIKeys.GeoCodeApi&callback=initMap" ,
        async defer></script>
<div>
    <h4>Leasor</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LasttName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LasttName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EmailAddress)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EmailAddress)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StreetAddress)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StreetAddress)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.City)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.City)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StateCode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StateCode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ZipCode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ZipCode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Lat)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Lat)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Lng)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Lng)
        </dd>

        

    </dl>
</div>
<p>
    @Html.ActionLink("Register an Item", "Create", "Items") |
    @Html.ActionLink("See My Items", "GetLeasorItems", new { id = Model.LeasorId }) |
    @Html.ActionLink("See My Reviews", "GetLeasorRatings", "Ratings", new { id = Model.LeasorId }, null) |
    @Html.ActionLink("Edit", "Edit", new { id = Model.LeasorId }) |
    @Html.ActionLink("Back to List", "Index") |
    
    @Html.ActionLink("Check Rent Periods", "UnRentItem", "Leasors") |
    @Html.ActionLink("Check RatingQueue", "GetRatingQueue", "Leasors")
</p>

RentX/Views/Leasors/GetItemQueue.cshtml
@model RentX.Models.ItemQueueViewModel
@using RentX.Models
@{
    ViewBag.Title = "GetItemQueue";
}

<h2>Item Queue</h2>


<table class="table">
    <tr>
        <td>
            @Html.DisplayNameFor(model => model.Renters[0].FirstName)
        </td>
        <td>
            @Html.DisplayNameFor(model => model.Renters[0].LasttName)
        </td>
    </tr>
@for (int i = 0; i < Model.Renters.Count; i++)
{
<tr>
    <td>
        @Html.DisplayFor(model => model.Renters[i].FirstName)
    </td>
    <td>
        @Html.DisplayFor(model => model.Renters[i].LasttName)
    </td>
    <td>
        @Html.ActionLink("See Renter Reviews", "GetRenterRatings", "Ratings", new { id = Model.Renters[i].RenterId }, null)
    </td>
    <td>
        @Html.ActionLink("Request Payment", "RequestRenterPayment", "Leasors", new { id = Model.Renters[i].RenterId, ItemId = Model.ItemId }, null)
    </td>
    <td>
        @Html.ActionLink("Rent out Item", "RentOutItem", "Leasors", new { id = Model.Renters[i].RenterId, ItemId = Model.ItemId }, null)
    </td>
</tr>
}
</table>   
@Html.ActionLink("Back", "Index", "Home")

RentX/Views/Leasors/GetLeasorItems.cshtml
@model IEnumerable<RentX.Models.Item>

@{
    ViewBag.Title = "GetLeasorItems";
}

<h2>GetLeasorItems</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Price)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Image)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.RentCounter)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Availability)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NumOfMonthsForRent)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.StartDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EndDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LeasorId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.RenterId)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
<tr>
    <td>
        @Html.DisplayFor(modelItem => item.Name)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Price)
    </td>
    <td>
        <img height="100" width="150" src="@Url.Content(item.Image)" />
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.RentCounter)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Availability)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.NumOfMonthsForRent)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.StartDate)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.EndDate)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.LeasorId)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.RenterId)
    </td>
    <td>
        @Html.ActionLink("Click to enter Queue", "AddSelfToQueue", "Renters", new { id = item.ItemId }, null)
    </td>
    <td>
        @Html.ActionLink("Click to see Queue", "GetItemQueue", "Leasors", new { id = item.ItemId }, null)
    </td>
</tr>
    }

</table>
@Html.ActionLink("Back to List", "Index")

RentX/Views/Leasors/GetRatingQueue.cshtml
@model IEnumerable<RentX.Models.RatingQueue>

@{
    ViewBag.Title = "GetRatingQueue";
}

<h2>GetRatingQueue</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.LeasorId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.RenterId)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.LeasorId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.RenterId)
        </td>
        <td>
            @Html.ActionLink("Give Review", "CreateRatingForLeasor", "Ratings", new { id = item.RenterId }, null ) |
            
        </td>
    </tr>
}

</table>